send_control_command:
  name: send_control_command
  description: send_control_command.
  target:
    entity:
      integration: wukongtv
      domain: media_player
  fields:
    code:
      example: tv_ok
      selector:
        select:
          options:
            - tv_connect
            - tv_up
            - tv_down
            - tv_left
            - tv_right
            - tv_home
            - tv_ok
            - tv_back
            - tv_volup
            - tv_voldown
            - tv_power
            - tv_menu
            - tv_0
            - tv_1
            - tv_2
            - tv_3
            - tv_4
            - tv_5
            - tv_6
            - tv_7
            - tv_8
            - tv_9

send_open_command:
  name: send_open_command
  description: send_open_command.
  target:
    entity:
      integration: wukongtv
      domain: media_player
  fields:
    appid:
      example: "nl.rogro82.pipup"
      selector:
        text:
  
send_install_command:
  name: send_install_command
  description: send_install_command.
  target:
    entity:
      integration: wukongtv
      domain: media_player
  fields:
    appurl:
      example: "http://192.168.8.2/apk/%E4%BA%91%E6%B5%B7%E7%94%B5%E8%A7%86_1.1.6_release.apk"
      selector:
        text:
  
send_clean_command:
  name: send_clean_command
  description: send_clean_command.
  target:
    entity:
      integration: wukongtv
      domain: media_player

  
send_command_queue:
  name: send_command_queue
  description: send_command_queue.
  target:
    entity:
      integration: wukongtv
      domain: media_player
  
send_connect_command:
  name: send_connect_command
  description: send_connect_command.
  target:
    entity:
      integration: wukongtv
      domain: media_player
  
send_pipup_command:
  name: send_pipup_command
  description: send_pipup_command.
  target:
    entity:
      integration: wukongtv
      domain: media_player
  fields:
    mediatype:
      example: "web"
      required: true
      selector:
        select:
          options:
            - text
            - web
    message:
      example: "this is the message"
      required: true
      selector:
        text:
    title:
      example: "title"
      selector:
        text:
    httpurl:
      example: "https://www.baidu.com/"
      selector:
        text:
    duration:
      example: 20
      selector:
        text:
    position:
      example: 0
      selector:
        select:
          options:
            - 0
            - 1
            - 2
            - 3
            - 4
    titlecolor:
      example: red
      selector:
        text:
    titlesize:
      example: 24
      selector:
        text:        
    messagecolor:
      example: white
      selector:
        text:
    messagesize:
      example: 16
      selector:
        text:
    backgroundcolor:
      example: black
      selector:
        text:
    width:
      example: 640
      selector:
        text:
    height:
      example: 480
      selector:
        text: